### PR TITLE
0.51 support

### PR DESCRIPTION
**Pull request by pogarek**

### CODE REVIEW

**Comment by marbink** [comment]
@pogarek Thanks for your help, man! But there is a little thing you need to correct in order to merge modifications. We should make users to have the possibility to not use 0.51 hash key and continue using 0.45 until it works.
So, please adapt your code to make 'hash_key' a not mandatory parameter. Thanks!

**Comment by pogarek** [comment]
Done :)

**Comment by pogarek** [comment]
Sorry , I read your answer as comment for another PR. I will do the change ,  as asked 😀

**Comment by pogarek** [comment]
Done. And added support for chrome in non-default directory .

**Pull request merged**
